name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pylint app.py --exit-zero  # Exit-zero to avoid failing the build on linting warnings

    - name: Run unit tests
      run: |
        python -m unittest test_app.py

    - name: Verify imports
      run: |
        python -c "import tkinter; print('Tkinter imported successfully')"
        python -c "import mysql.connector; print('MySQL Connector imported successfully')"