name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-database-operations:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: '@Mamdouh2'
          MYSQL_DATABASE: Library
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Database Tests
      run: |
        python -m pytest test_db_operations.py --cov=. --cov-report=xml --cov-report=term-missing
    - name: Upload Database Coverage
      uses: actions/upload-artifact@v4
      with:
        name: database-coverage
        path: coverage.xml

  test-gui-operations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb python3-tk
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run GUI Tests
      run: |
        xvfb-run --auto-servernum python -m pytest test_gui_operations.py --cov=. --cov-report=xml --cov-report=term-missing
    - name: Upload GUI Coverage
      uses: actions/upload-artifact@v4
      with:
        name: gui-coverage
        path: coverage.xml

  combine-coverage:
    needs: [test-database-operations, test-gui-operations]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Download Database Coverage
      uses: actions/download-artifact@v4
      with:
        name: database-coverage
        path: ./coverage-db
    - name: Download GUI Coverage
      uses: actions/download-artifact@v4
      with:
        name: gui-coverage
        path: ./coverage-gui
    - name: Combine Coverage Reports
      run: |
        coverage combine ./coverage-db/coverage.xml ./coverage-gui/coverage.xml
        coverage report
        coverage xml
    - name: Upload Combined Coverage
      uses: actions/upload-artifact@v4
      with:
        name: combined-coverage
        path: coverage.xml
